#!/usr/bin/env python
import os
import time
import threading

from bottle import route, run, static_file, template, request, redirect, post
from opqwifi.WIFIutill.wifi_ssids import wifi_ssids
from opqwifi.WIFIutill.wifi_connect import wifi_connect
from opqwifi.WIFIutill.wifi_check import wifi_check
from opqwifi.WIFIutill.wifi_ap import wifi_ap
from opqwifi.WIFIutill.wifi_wait import wifi_wait
wifi_list = []

@route('/js/<filename>')
def js_static(filename):
    return static_file(filename, root=os.path.join(os.path.dirname(__file__), "../../opqwifi/js/"))


@route('/img/<filename>')
def img_static(filename):
    return static_file(filename, root=os.path.join(os.path.dirname(__file__), "../../opqwifi/img/"))


@route('/css/<filename>')
def img_static(filename):
    return static_file(filename, root=os.path.join(os.path.dirname(__file__), "../../opqwifi/css/"))

@route("/")
def networks():
    return template(os.path.join(os.path.dirname(__file__), "../../opqwifi/views/networks.tpl"), ssids=wifi_list)

@post("/")
def connect():
    if request.POST.get("sub_OPEN","").strip():
        mSSID = request.forms.get('fOPEN')


    elif request.POST.get("sub_WPA","").strip():
        password = request.forms.get('pwdWPA')
        mSSID = request.forms.get('fWPA')
        wifi_ap(False, "wlan0")
        wifi_connect({"ssid" : mSSID, "Sec" : "WPA", "password" : password})

    elif request.POST.get("sub_WEP","").strip():
        password = request.forms.get('pwdWEP')
        mSSID = request.forms.get('fWEP')
    redirect("/")

def run_server(host='0.0.0.0', port=80):
    port = int(os.environ.get("PORT", port))
    run(host=host, port=port)

def timer_func():
    if not wifi_check():
        print "No connection."
        wifi_ap(True, "wlan0")
    else:
        print "Connection."

wifi_wait()
time.sleep(5)
wifi_list = wifi_ssids()
timer = threading.Timer(60, timer_func)
timer.start()
run_server()
